spring:
  datasource:
    url: jdbc:sqlserver://freekaserver.database.windows.net:1433;database=freedatabase;user=aniket123456@freekaserver;password=aniket@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: aniket123456
    password: aniket@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9193


